name: PlatformIO workflow

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Run PlatformIO CI
        run: pio ci -c platformio.ini .
